# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for zeroltexx configurations
Name: jolla-configuration-zeroltexx
Requires:
- pattern:jolla-hw-adaptation-zeroltexx
- patterns-sailfish-applications
- patterns-sailfish-ui
# For devices with cellular modem. Those without one, please comment out:
- patterns-sailfish-cellular-apps
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

- sailfish-content-graphics-z@ICON_RES@

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

# For Mozilla location services (online)
- geoclue-provider-mlsdb

# Sailfish OS CSD tool for hardware testing
# needs some configuration to get all features working
- csd

# Introduced starting Sailfish OS 2.1.1.26
# Required for Jolla Store Access
- patterns-sailfish-consumer-generic

# Devices with 2G or more memory should also include this booster
# to improve camera startup times and the like
- mapplauncherd-booster-silica-qt5-media

# some apps useful
- sailfish-office
- jolla-calculator
- jolla-email
- jolla-notes
- jolla-clock
- jolla-mediaplayer
- jolla-calendar
- sailfish-weather

Summary: Jolla Configuration zeroltexx
